parser: "@typescript-eslint/parser"

env:
  node: true

root: true

parserOptions:
  ecmaVersion: 2022
  project: tsconfig.json
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - simple-import-sort

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-native/all
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

rules:
  simple-import-sort/imports: "error"
  simple-import-sort/exports: "error"
  sort-imports: "off"

settings:
  react:
    version: detect

ignorePatterns:
  - babel.config.js
  - generated
