/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	DateTime: "String",
	DateTimeFilter:{
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	DateTimeNullableFilter:{
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	DateTimeNullableWithAggregatesFilter:{
		_count:{
			type:"NestedIntNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeNullableWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	DateTimeWithAggregatesFilter:{
		_count:{
			type:"NestedIntFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedDateTimeFilter:{
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedDateTimeNullableFilter:{
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedDateTimeNullableWithAggregatesFilter:{
		_count:{
			type:"NestedIntNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedDateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeNullableWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedDateTimeWithAggregatesFilter:{
		_count:{
			type:"NestedIntFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedDateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"DateTime",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedDateTimeWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"DateTime",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedIntFilter:{
		equals:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedIntFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedIntNullableFilter:{
		equals:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedIntNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	NestedStringFilter:{
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	NestedStringWithAggregatesFilter:{
		_count:{
			type:"NestedIntFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationCountOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationMaxOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationMinOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationOrderByWithAggregationInput:{
		_count:{
			type:"OrganizationCountOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"OrganizationMaxOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"OrganizationMinOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationOrderByWithRelationInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationScalarFieldEnum: "enum",
	OrganizationScalarWhereWithAggregatesInput:{
		AND:{
			type:"OrganizationScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"OrganizationScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"OrganizationScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt:{
			type:"DateTimeWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"StringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationWhereInput:{
		AND:{
			type:"OrganizationWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"OrganizationWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"OrganizationWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt:{
			type:"DateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	OrganizationWhereUniqueInput:{
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Query:{
		aggregateOrganization:{
			cursor:{
				type:"OrganizationWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"OrganizationOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"OrganizationWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		aggregateUser:{
			cursor:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"UserOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		findFirstOrganization:{
			cursor:{
				type:"OrganizationWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			distinct:{
				type:"OrganizationScalarFieldEnum",
				array:true,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OrganizationOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"OrganizationWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		findFirstUser:{
			cursor:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			distinct:{
				type:"UserScalarFieldEnum",
				array:true,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"UserOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		groupByOrganization:{
			by:{
				type:"OrganizationScalarFieldEnum",
				array:true,
				arrayRequired:true,
				required:true
			},
			having:{
				type:"OrganizationScalarWhereWithAggregatesInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"OrganizationOrderByWithAggregationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"OrganizationWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		groupByUser:{
			by:{
				type:"UserScalarFieldEnum",
				array:true,
				arrayRequired:true,
				required:true
			},
			having:{
				type:"UserScalarWhereWithAggregatesInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			orderBy:{
				type:"UserOrderByWithAggregationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		organization:{
			where:{
				type:"OrganizationWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		organizations:{
			cursor:{
				type:"OrganizationWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			distinct:{
				type:"OrganizationScalarFieldEnum",
				array:true,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"OrganizationOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"OrganizationWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user:{
			where:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		users:{
			cursor:{
				type:"UserWhereUniqueInput",
				array:false,
				arrayRequired:false,
				required:false
			},
			distinct:{
				type:"UserScalarFieldEnum",
				array:true,
				arrayRequired:false,
				required:true
			},
			orderBy:{
				type:"UserOrderByWithRelationInput",
				array:true,
				arrayRequired:false,
				required:true
			},
			skip:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			take:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"UserWhereInput",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	QueryMode: "enum",
	SortOrder: "enum",
	StringFilter:{
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mode:{
			type:"QueryMode",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	StringWithAggregatesFilter:{
		_count:{
			type:"NestedIntFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"NestedStringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		endsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		equals:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		mode:{
			type:"QueryMode",
			array:false,
			arrayRequired:false,
			required:false
		},
		not:{
			type:"NestedStringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		notIn:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		startsWith:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserCountOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserMaxOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserMinOrderByAggregateInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserOrderByWithAggregationInput:{
		_count:{
			type:"UserCountOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		_max:{
			type:"UserMaxOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		_min:{
			type:"UserMinOrderByAggregateInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserOrderByWithRelationInput:{
		createdAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"SortOrder",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserScalarFieldEnum: "enum",
	UserScalarWhereWithAggregatesInput:{
		AND:{
			type:"UserScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"UserScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"UserScalarWhereWithAggregatesInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt:{
			type:"DateTimeWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"StringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"DateTimeNullableWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"StringWithAggregatesFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserWhereInput:{
		AND:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		NOT:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		OR:{
			type:"UserWhereInput",
			array:true,
			arrayRequired:false,
			required:true
		},
		createdAt:{
			type:"DateTimeFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		emailVerifiedAt:{
			type:"DateTimeNullableFilter",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"StringFilter",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	UserWhereUniqueInput:{
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	AggregateOrganization:{
		_count:"OrganizationCountAggregate",
		_max:"OrganizationMaxAggregate",
		_min:"OrganizationMinAggregate"
	},
	AggregateUser:{
		_count:"UserCountAggregate",
		_max:"UserMaxAggregate",
		_min:"UserMinAggregate"
	},
	Organization:{
		createdAt:"DateTime",
		id:"String",
		name:"String"
	},
	OrganizationCountAggregate:{
		_all:"Int",
		createdAt:"Int",
		id:"Int",
		name:"Int"
	},
	OrganizationGroupBy:{
		_count:"OrganizationCountAggregate",
		_max:"OrganizationMaxAggregate",
		_min:"OrganizationMinAggregate",
		createdAt:"DateTime",
		id:"String",
		name:"String"
	},
	OrganizationMaxAggregate:{
		createdAt:"DateTime",
		id:"String",
		name:"String"
	},
	OrganizationMinAggregate:{
		createdAt:"DateTime",
		id:"String",
		name:"String"
	},
	Query:{
		aggregateOrganization:"AggregateOrganization",
		aggregateUser:"AggregateUser",
		findFirstOrganization:"Organization",
		findFirstUser:"User",
		groupByOrganization:"OrganizationGroupBy",
		groupByUser:"UserGroupBy",
		organization:"Organization",
		organizations:"Organization",
		user:"User",
		users:"User"
	},
	User:{
		createdAt:"DateTime",
		email:"String",
		emailVerifiedAt:"DateTime",
		id:"String"
	},
	UserCountAggregate:{
		_all:"Int",
		createdAt:"Int",
		email:"Int",
		emailVerifiedAt:"Int",
		id:"Int"
	},
	UserGroupBy:{
		_count:"UserCountAggregate",
		_max:"UserMaxAggregate",
		_min:"UserMinAggregate",
		createdAt:"DateTime",
		email:"String",
		emailVerifiedAt:"DateTime",
		id:"String"
	},
	UserMaxAggregate:{
		createdAt:"DateTime",
		email:"String",
		emailVerifiedAt:"DateTime",
		id:"String"
	},
	UserMinAggregate:{
		createdAt:"DateTime",
		email:"String",
		emailVerifiedAt:"DateTime",
		id:"String"
	}
}